export const timeSeriesUploadTitle = 'Upload your time series data (CSV format)'
export const timeSeriesUploadSubtitle = 'Download Target Example Data'
export const timeSeriesUploadExampleLink = 'https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/electricity.csv'
export const exogenousUploadTitle = 'Upload your exogenous data (CSV format)'
export const exogenousUploadSubtitle = 'Download Exogenous Variables Example Data'
export const exogenousUploadExampleLink = 'https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/exogenous-vars-electricity.csv'
